# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-03 15:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20170203_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='participating_users',
            field=models.ManyToManyField(blank=True, related_name='participant', to=settings.AUTH_USER_MODEL),
        ),
    ]
