version: '2.0'
services:
  nginx:
    build: ./nginx
    volumes_from:
      - django
    links:
      - django
    ports:
      - "8080:80"
  django:
    build: .
    volumes:
      - .:/usr/src/app
