version: '2.0'
services:
  django:
    links:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=hackathon.settings.production
    command: /usr/bin/production-entrypoint.sh
  db:
    image: postgres
