version: '2.0'
services:
  django:
    links:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=hackathon.settings.production
    command: /usr/local/bin/gunicorn hackathon.wsgi:application -w 2 -b :8000
  db:
    image: postgres
